const BRONZE_TITLE = 'B';
const SILVER_TITLE = 'S';
const GOLD_TITLE = 'G';
const PLATINUM_TITLE = 'P';
const DIAMOND_TITLE = 'D';
const MASTER_TITLE = 'M';
const GRAND_MASTER_TITLE = 'GM';

const SILVER_POINT = 2000;
const GOLD_POINT = 3000;
const PLATINUM_POINT = 4000;
const DIAMOND_POINT = 5000;
const MASTER_POINT = 6000;
const GRAND_MASTER_POINT = 7000;

export {
	BRONZE_TITLE,
	SILVER_TITLE,
	GOLD_TITLE,
	PLATINUM_TITLE,
	DIAMOND_TITLE,
	MASTER_TITLE,
	GRAND_MASTER_TITLE,
	SILVER_POINT,
	GOLD_POINT,
	PLATINUM_POINT,
	DIAMOND_POINT,
	MASTER_POINT,
	GRAND_MASTER_POINT,
};
